/*
 * Minimal FreeRTOS example for dsPIC33AK128MC.
 *
 * One task toggles a GPIO pin every 500ms. Everything else (tick timer,
 * idle/stack-overflow hooks, static task memory) is handled by the
 * official Microchip dsPIC33A FreeRTOS port in FreeRTOS/portable/MPLAB/dsPIC33A/.
 *
 * >>> Adjust LED_TRIS / LED_LAT below to match a real pin on your board. <<<
 * This example defaults to RA0. If you already have pin config generated by
 * MCC (Pin Grid View), replace this with your MCC pin macros instead, and
 * skip the TRISA/LATA lines here - just keep the toggle logic in the task.
 */

#include <xc.h>
#include "FreeRTOS.h"
#include "task.h"

#define LED_TRIS    TRISAbits.TRISA0
#define LED_LAT     LATAbits.LATA0

static void vClockInitialise( void );
static void vBlinkTask( void *pvParameters );

int main( void )
{
    vClockInitialise();

    LED_TRIS = 0;   /* RA0 as output */
    LED_LAT  = 0;

    xTaskCreate( vBlinkTask, "Blink", configMINIMAL_STACK_SIZE, NULL,
                 tskIDLE_PRIORITY + 1, NULL );

    vTaskStartScheduler();

    /* Only reached if there was insufficient heap to start the scheduler. */
    for( ;; )
    {
    }

    return 0;
}
/*-----------------------------------------------------------*/

static void vBlinkTask( void *pvParameters )
{
    ( void ) pvParameters;

    for( ;; )
    {
        LED_LAT ^= 1;
        vTaskDelay( pdMS_TO_TICKS( 500 ) );
    }
}
/*-----------------------------------------------------------*/

void vApplicationIdleHook( void )
{
    /* configUSE_IDLE_HOOK is 1, so this must exist - nothing to do here. */
}
/*-----------------------------------------------------------*/

/*
 * Clock init copied verbatim from Microchip's official dsPIC33AK128MC106
 * FreeRTOS demo (pic24-dspic33-freertos-demo repo). Configures FRC + PLL1
 * for a 50 MHz Fosc, matching configCPU_CLOCK_HZ in FreeRTOSConfig.h.
 *
 * If you already have MCC-generated clock configuration for your board,
 * use that instead and delete this function - just make sure
 * configCPU_CLOCK_HZ still matches whatever Fosc you end up with.
 */
static void vClockInitialise( void )
{
    FRCTUN = 0x0UL;
    BFRCTUN = 0x0UL;

    OSCCTRLbits.FRCEN = 1U;
    while( OSCCTRLbits.FRCRDY == 0U ) {};
    OSCCTRLbits.BFRCEN = 1U;
    while( OSCCTRLbits.BFRCRDY == 0U ) {};

    PLL1CON = 0x9100UL;
    PLL1DIV = 0x1007D29UL;
    PLL1CONbits.PLLSWEN = 1U;
    while( PLL1CONbits.PLLSWEN == 1 ) {};
    PLL1CONbits.FOUTSWEN = 1U;
    while( PLL1CONbits.FOUTSWEN == 1U ) {};
    PLL1CONbits.OSWEN = 1U;
    while( PLL1CONbits.OSWEN == 1U ) {};
    while( OSCCTRLbits.PLL1RDY == 0U ) {};

    VCO1DIV = 0x0UL;
    PLL1CONbits.DIVSWEN = 1U;
    while( PLL1CONbits.DIVSWEN == 1U ) {};

    CLK1CON = 0x19500UL;
    CLK1DIV = 0x20000UL;
    CLK1CONbits.DIVSWEN = 1U;
    while( CLK1CONbits.DIVSWEN == 1U ) {};
    CLK1CONbits.OSWEN = 1U;
    while( CLK1CONbits.OSWEN == 1U ) {};

    CLK2CON = 0x19101UL;
    CLK2CONbits.OSWEN = 1U;
    while( CLK2CONbits.OSWEN == 1U ) {};

    CLK3CON = 0x29202UL;
    CLK3CONbits.OSWEN = 1U;
    while( CLK3CONbits.OSWEN == 1U ) {};

    CLK8CON = 0x9100UL;
    CLK8DIV = 0x0UL;
    CLK8CONbits.OSWEN = 1U;
    while( CLK8CONbits.OSWEN == 1U ) {};
}
